NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation.

At the core of the NumPy package, is the ndarray object

1.   NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
2.   The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.
3.    NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
4.    A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-   sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.



In [1]:
import numpy as np
array1=np.array([1,2,3,5])
array1

array([1, 2, 3, 5])

In [2]:
array1.dtype

dtype('int64')

Data types
bool_
int_
uint8
float16
complex
object

List to NPArray

In [5]:
list_of_item =[1,2,3,4]
array2=np.array(list_of_item)
array2

array([1, 2, 3, 4])

Numpy is ND Array


In [6]:
array3=np.array([[1,2,3],[4,5,6],[7,8,9]])
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Rank of an numpy array
use ndim

In [7]:
array3.ndim

2

To Find shape of n dimensional array i.e. rows and columns

In [8]:
array3.shape

(3, 3)

To find the number of elements in array use size attribute

In [9]:
array3.size

9

To Identify the datatype of array use dtype

In [10]:
array3.dtype

dtype('int64')

To identify the memory size of each item use itemsize attribute

In [11]:
array3.itemsize

8

To find the location of array

In [12]:
array3.data

**Accessing the elements in numpy array**

In [13]:
array5 = np.array([4,5,6,7])
array5

array([4, 5, 6, 7])

To access the elements use idices starting from 0


In [14]:
array5[0]

4

In [15]:
array5[3]

7

You can also start from end...in that case you have to use negative indices starting from -1 that is the last element



In [16]:
array5[-1]

7

In [0]:
a1=np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])

In [21]:
a1

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Use row, column indices to access 2 d array

In [22]:
a1[0][1]

2

use negative indices for starting from end


In [24]:
a1[-3][-3]

2

Use can also get subarrays from arrays

use [index:no of elements]

In [37]:


print(array5)

print(array5[0:2])

[4 5 6 7]
[4 5]


In [39]:
a1

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
x=a1[0:2,0:2]

In [43]:
x

array([[1, 2],
       [4, 5]])

you can use base attribute to get parent array

In [44]:
x.base

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

You can use slicing also.

This will give you all rows and columns starting from 0 upto 2 elements

In [45]:
a1[:,0:2]

array([[1, 2],
       [4, 5],
       [8, 9]])

In [46]:
a1[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

to assign values to all elements from particular row

In [48]:

a1[1:]=20
a1

array([[ 1,  2,  3,  4],
       [20, 20, 20, 20],
       [20, 20, 20, 20]])

In [49]:
a1[1:]=[[1,1,1,1],[2,2,3,4]]
a1

array([[1, 2, 3, 4],
       [1, 1, 1, 1],
       [2, 2, 3, 4]])

Short codes to create array of 0s

In [52]:
c=np.zeros([3,2])
c

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Default value will be float


In [53]:
c.dtype

dtype('float64')

In [54]:
d=np.ones([2,2])
d

array([[1., 1.],
       [1., 1.]])

To use specific datatype, you have to use dtype

In [55]:
e=np.ones([3,2],dtype=int)
e

array([[1, 1],
       [1, 1],
       [1, 1]])

array with random values but random values will be less than 1

In [56]:
f=np.empty([3,2])
f

array([[1.36661087e-316, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

You can use arange for incemental or decremental values
np.arrange(start_no,end_no,step)

In [58]:
g=np.arange(0,12,2)
g

array([ 0,  2,  4,  6,  8, 10])

You can use linespace function as well for evenly distribution of squence


In [64]:
h=np.linspace(start=0,stop=10,num=4)
h

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

Complex number array


In [65]:
cm=np.array([[1,2],[2,3],[4,5]],dtype=complex)
cm

array([[1.+0.j, 2.+0.j],
       [2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j]])

In [67]:
n=np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You can reshape the array

In [68]:
n=n.reshape(2,5)
n

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])